name: Minimal CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - CONTRIBUTING.md
      - docs/**
      - mkdocs.yml

jobs:
  test:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@update-windows-gh-workspace
    with:
      os: ubuntu-latest
      py3version: "12"
      notebook_kernel: python_boilerplate
      lint: false