name: Daily CI

on:
  schedule:
    - cron: '23 14 * * 1-5'

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Add date to github output env
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  test:
    needs: get-date
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@force-python-version
    with:
      os: ubuntu-latest
      py3version: "12"
      notebook_kernel: python_boilerplate
      pytest_args: '--no-cov'  # ignore coverage
      cache_mamba_env: false
      lint: false
      mamba_env_name: daily-ci