name: Development docs CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - tests/**

jobs:
  docs-test:
    if: github.ref != 'refs/heads/main'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@setup-micromamba-to-miniconda
    with:
      deploy_type: test
      notebook_kernel: python_boilerplate

  docs-update-latest:
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@setup-micromamba-to-miniconda
    with:
      deploy_type: update_latest
      notebook_kernel: python_boilerplate