name: Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - CONTRIBUTING.md
      - docs/**
      - mkdocs.yml

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        py3version: ["10", "12"]
      fail-fast: false
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@update-windows-gh-workspace
    with:
      os: ${{ matrix.os }}
      py3version: ${{ matrix.py3version }}
      notebook_kernel: python_boilerplate
      lint: false
      pytest_args: '--no-cov'  # ignore coverage
      upload_to_codecov: false

  test-coverage:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@update-windows-gh-workspace
    with:
      os: ubuntu-latest
      py3version: "12"
      notebook_kernel: python_boilerplate
      lint: false
      pytest_args: 'tests/'  # ignore example notebooks
      upload_to_codecov: true

  memory-profile:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-memory-profile.yml@update-windows-gh-workspace
    with:
      py3version: "12"
      upload_flamegraph: true

  cruft-check:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/template-check.yml@update-windows-gh-workspace
