name: Build Package

on:
  push:
    tags:
      - 'v*'

jobs:
  conda-build:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-build.yml@add-conda-build-args
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    with:
      package_name: bryn_python_boilerplate

  pip-build:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/pip-build.yml@add-pip-upload
    with:
      package_name: bryn_python_boilerplate