name: Build Package

on:
  push:
    tags:
      - 'v*'

jobs:
  conda-build:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-build.yml@fix-input-refs
    with:
      package_name: python_boilerplate