name: Publish

on:
  release:
    types: [released]

jobs:
  conda-upload:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-upload.yml@fix-input-refs
    secrets: inherit
    with:
      package_name: python_boilerplate

  docs-stable:
    permissions:
      contents: write
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@update-docs-deploy
    with:
      deploy_type: update_stable
      notebook_kernel: python_boilerplate